<a href="https://colab.research.google.com/github/uzeziogho/MLDM/blob/main/Association_rules_mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install apyori
!pip install xlrd
!pip install utils

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5973 sha256=29f777eb5afa649cffac50e72d5ff1ed0879c881e39f07dfc28a11fa3e1c8118
  Stored in directory: /root/.cache/pip/wheels/cb/f6/e1/57973c631d27efd1a2f375bd6a83b2a616c4021f24aab84080
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: xlrd in /usr/local/lib/python3.7/dist-packages (1.1.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting utils
  Downloading utils-1.0.1-py2.py3-none-any.whl (21 kB)
Installing collected packages: utils
Successfully installed utils-1.0.1

In [ ]:
#import libraries
import matplotlib.pyplot as plt
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
#from mlxtend.frequent_patterns import apriori


from apyori import apriori
import utils
%matplotlib inline

In [ ]:
#Load dataset
obesity_data=pd.read_csv('/content/ObesityDataSet_raw_and_data_sinthetic.csv')
#dishonesty_data.columns=["CT","CU","LT","TC","TS"]

In [ ]:
#Analyse dataset
obesity_data.head(10)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II
5,Male,29.0,1.62,53.0,no,yes,2.0,3.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Automobile,Normal_Weight
6,Female,23.0,1.50,55.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,0.0,Sometimes,Motorbike,Normal_Weight
7,Male,22.0,1.64,53.0,no,no,2.0,3.0,Sometimes,no,2.0,no,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
8,Male,24.0,1.78,64.0,yes,yes,3.0,3.0,Sometimes,no,2.0,no,1.0,1.0,Frequently,Public_Transportation,Normal_Weight
9,Male,22.0,1.72,68.0,yes,yes,2.0,3.0,Sometimes,no,2.0,no,1.0,1.0,no,Public_Transportation,Normal_Weight

In [ ]:
obesity_data = obesity_data.drop(columns=['Age','Height','Weight'])

In [ ]:
#creating sample transactions
transactions=[
    ['Female','yes','no','2.0','3.0','Sometimes','yes','1.0','no','2.0','Frequently','Motorbike','Normal_Weight'],
    ['Male','yes','no','1.0','2.0','Always','no','3.0','yes','1.0','Sometimes','Automobile','Insufficient_Weight'],
    ['Female','no','no','1.0','2.0','Never','yes','2.0','no','3.0','Sometimes','Walking','Obesity_Type_II'],
    ['Male','yes','yes','1.0','2.0','Sometimes','yes','1.0','yes','1.0','Always','Public_Transportation','Overweight_Level_I'],
    ['Male','yes','no','1.0','3.0','Always','no','2.0','yes','2.0','No','Public_Transportation','Obesity_Type_III'],
    ['Female','no','no','1.0','2.0','Sometimes','yes','3.0','yes','1.0','Sometimes','Automobile','Obesity_Type_I'],
    ['Male','yes','no','1.0','1.0','Sometimes','no','1.0','no','3.0','Sometimes','Public_Transportation','Overweight_Level_II'],
]
transactions

[['Female',
  'yes',
  'no',
  '2.0',
  '3.0',
  'Sometimes',
  'yes',
  '1.0',
  'no',
  '2.0',
  'Frequently',
  'Motorbike',
  'Normal_Weight'],
 ['Male',
  'yes',
  'no',
  '1.0',
  '2.0',
  'Always',
  'no',
  '3.0',
  'yes',
  '1.0',
  'Sometimes',
  'Automobile',
  'Insufficient_Weight'],
 ['Female',
  'no',
  'no',
  '1.0',
  '2.0',
  'Never',
  'yes',
  '2.0',
  'no',
  '3.0',
  'Sometimes',
  'Walking',
  'Obesity_Type_II'],
 ['Male',
  'yes',
  'yes',
  '1.0',
  '2.0',
  'Sometimes',
  'yes',
  '1.0',
  'yes',
  '1.0',
  'Always',
  'Public_Transportation',
  'Overweight_Level_I'],
 ['Male',
  'yes',
  'no',
  '1.0',
  '3.0',
  'Always',
  'no',
  '2.0',
  'yes',
  '2.0',
  'No',
  'Public_Transportation',
  'Obesity_Type_III'],
 ['Female',
  'no',
  'no',
  '1.0',
  '2.0',
  'Sometimes',
  'yes',
  '3.0',
  'yes',
  '1.0',
  'Sometimes',
  'Automobile',
  'Obesity_Type_I'],
 ['Male',
  'yes',
  'no',
  '1.0',
  '1.0',
  'Sometimes',
  'no',
  '1.0',
  'no',
  '3.0',
  'Sometimes',
  'Public_Transportation',
  'Overweight_Level_II']]

In [ ]:
# Generating association rules
Rules = list(apriori(transactions, min_support=0.5, min_confidence=0.25,min_lift=2, min_length=2))

In [ ]:
#Extract the created rules
#associationRules=utils.extract(Rules)
#rules_TR=pd.DataFrame(associationRules,columns=['LHS','RHS','Support','Confidence','Lift'])
#rules_TR

AttributeError: ignored

In [ ]:
for i in range(len(Rules)):
    LHS=list(Rules[i][2][0][0])
    RHS=list(Rules[i][2][0][1])
    support=Rules[i][1]
    confidence=Rules[i][2][0][2]
    lift=Rules[i][2][0][3]
    print("LHS:",LHS,"--","RHS:",RHS)
    print("Support:",support)
    print("Confidence:",confidence)
    print("Lift:",lift)
    print(10*"----")

In [ ]:
#transactions=utils.data_prepare(dishonesty_data)

AttributeError: ignored

In [ ]:
dte = TransactionEncoder()
dte_ary = dte.fit(obesity_data).transform(obesity_data)
disf = pd.DataFrame(dte_ary, columns=dte.columns_)
disf

,2,A,C,E,F,G,H,K,L,M,...,l,m,n,o,r,s,t,v,w,y
0,False,False,False,False,False,True,False,False,False,False,...,False,False,True,False,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,True,False,True,True,True,True,True,True,True
2,False,True,True,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,True,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2107,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2108,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2109,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2110,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
#Return item and itemsets with support of 60%
apriori(disf, min_support=0.00000000015,use_colnames=True)

In [ ]:
frequent_itemsets = apriori(disf, min_support=0.00045, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))
frequent_itemsets

    support itemsets  length
0  0.009317      (C)       1
1  0.003106      (L)       1
2  0.003106      (S)       1
3  0.012422      (T)       1
4  0.003106      (U)       1
5  0.006211   (C, T)       2
6  0.003106   (C, U)       2
7  0.003106   (L, T)       2
8  0.003106   (S, T)       2

In [ ]:
frequent_itemsets[ (frequent_itemsets['length'] == 2) &
                   (frequent_itemsets['support'] >= 0.8) ]

Empty DataFrame
Columns: [support, itemsets, length]
Index: []